/* IMPORTANT
 * This snapshot file is auto-generated, but designed for humans.
 * It should be checked into source control and tracked carefully.
 * Re-generate by setting TAP_SNAPSHOT=1 and running tests.
 * Make sure to inspect the output below.  Do not ignore changes!
 */
'use strict'
exports[`test/index.ts TAP > primordials object 1`] = `
Object {
  "AggregateError": "<<undefined in node 14>>",
  "AggregateErrorLength": "<<undefined in node 14>>",
  "AggregateErrorName": "<<undefined in node 14>>",
  "AggregateErrorPrototype": "<<undefined in node 14>>",
  "AggregateErrorPrototypeMessage": "<<undefined in node 14>>",
  "AggregateErrorPrototypeName": "<<undefined in node 14>>",
  "applyBind": Function bound bind(),
  "Array": Function Array(),
  "ArrayBuffer": Function ArrayBuffer(),
  "ArrayBufferGetSymbolSpecies": Function bound call(),
  "ArrayBufferIsView": Function bound call(),
  "ArrayBufferLength": 1,
  "ArrayBufferName": "ArrayBuffer",
  "ArrayBufferPrototype": Object {},
  "ArrayBufferPrototypeGetByteLength": Function bound call(),
  "ArrayBufferPrototypeSlice": Function bound call(),
  "ArrayBufferPrototypeSymbolToStringTag": "ArrayBuffer",
  "ArrayFrom": Function (...args),
  "ArrayGetSymbolSpecies": Function bound call(),
  "ArrayIsArray": Function (...args),
  "ArrayIterator": Object {
    "prototype": Object {},
  },
  "ArrayIteratorPrototype": "<<seen>>",
  "ArrayIteratorPrototypeNext": Function bound call(),
  "ArrayIteratorPrototypeSymbolToStringTag": "Array Iterator",
  "ArrayLength": 1,
  "ArrayName": "Array",
  "ArrayOf": Function (...args),
  "ArrayOfApply": Function bound apply(),
  "ArrayPrototype": Object {},
  "ArrayPrototypeConcat": Function bound call(),
  "ArrayPrototypeCopyWithin": Function bound call(),
  "ArrayPrototypeEntries": Function bound call(),
  "ArrayPrototypeEvery": Function bound call(),
  "ArrayPrototypeFill": Function bound call(),
  "ArrayPrototypeFilter": Function bound call(),
  "ArrayPrototypeFind": Function bound call(),
  "ArrayPrototypeFindIndex": Function bound call(),
  "ArrayPrototypeFlat": Function bound call(),
  "ArrayPrototypeFlatMap": Function bound call(),
  "ArrayPrototypeForEach": Function bound call(),
  "ArrayPrototypeIncludes": Function bound call(),
  "ArrayPrototypeIndexOf": Function bound call(),
  "ArrayPrototypeJoin": Function bound call(),
  "ArrayPrototypeKeys": Function bound call(),
  "ArrayPrototypeLastIndexOf": Function bound call(),
  "ArrayPrototypeLength": 0,
  "ArrayPrototypeMap": Function bound call(),
  "ArrayPrototypePop": Function bound call(),
  "ArrayPrototypePush": Function bound call(),
  "ArrayPrototypePushApply": Function bound apply(),
  "ArrayPrototypeReduce": Function bound call(),
  "ArrayPrototypeReduceRight": Function bound call(),
  "ArrayPrototypeReverse": Function bound call(),
  "ArrayPrototypeShift": Function bound call(),
  "ArrayPrototypeSlice": Function bound call(),
  "ArrayPrototypeSome": Function bound call(),
  "ArrayPrototypeSort": Function bound call(),
  "ArrayPrototypeSplice": Function bound call(),
  "ArrayPrototypeSymbolIterator": Function bound call(),
  "ArrayPrototypeSymbolUnscopables": Object {
    "at": true,
    "copyWithin": true,
    "entries": true,
    "fill": true,
    "find": true,
    "findIndex": true,
    "findLast": true,
    "findLastIndex": true,
    "flat": true,
    "flatMap": true,
    "includes": true,
    "keys": true,
    "values": true,
  },
  "ArrayPrototypeToLocaleString": Function bound call(),
  "ArrayPrototypeToString": Function bound call(),
  "ArrayPrototypeUnshift": Function bound call(),
  "ArrayPrototypeUnshiftApply": Function bound apply(),
  "ArrayPrototypeValues": Function bound call(),
  "AsyncIteratorPrototype": Object {},
  "BigInt": Function BigInt(),
  "BigInt64Array": Function BigInt64Array(),
  "BigInt64ArrayBYTES_PER_ELEMENT": 8,
  "BigInt64ArrayLength": 3,
  "BigInt64ArrayName": "BigInt64Array",
  "BigInt64ArrayPrototype": Object {},
  "BigInt64ArrayPrototypeBYTES_PER_ELEMENT": 8,
  "BigIntAsIntN": Function bound call(),
  "BigIntAsUintN": Function bound call(),
  "BigIntLength": 1,
  "BigIntName": "BigInt",
  "BigIntPrototype": Object {},
  "BigIntPrototypeSymbolToStringTag": "BigInt",
  "BigIntPrototypeToLocaleString": Function bound call(),
  "BigIntPrototypeToString": Function bound call(),
  "BigIntPrototypeValueOf": Function bound call(),
  "BigUint64Array": Function BigUint64Array(),
  "BigUint64ArrayBYTES_PER_ELEMENT": 8,
  "BigUint64ArrayLength": 3,
  "BigUint64ArrayName": "BigUint64Array",
  "BigUint64ArrayPrototype": Object {},
  "BigUint64ArrayPrototypeBYTES_PER_ELEMENT": 8,
  "Boolean": Function Boolean(),
  "BooleanLength": 1,
  "BooleanName": "Boolean",
  "BooleanPrototype": Object {},
  "BooleanPrototypeToString": Function bound call(),
  "BooleanPrototypeValueOf": Function bound call(),
  "clearInterval": Function clearInterval(timer),
  "clearTimeout": Function clearTimeout(timer),
  "DataView": Function DataView(),
  "DataViewLength": 1,
  "DataViewName": "DataView",
  "DataViewPrototype": Object {},
  "DataViewPrototypeGetBigInt64": Function bound call(),
  "DataViewPrototypeGetBigUint64": Function bound call(),
  "DataViewPrototypeGetBuffer": Function bound call(),
  "DataViewPrototypeGetByteLength": Function bound call(),
  "DataViewPrototypeGetByteOffset": Function bound call(),
  "DataViewPrototypeGetFloat32": Function bound call(),
  "DataViewPrototypeGetFloat64": Function bound call(),
  "DataViewPrototypeGetInt16": Function bound call(),
  "DataViewPrototypeGetInt32": Function bound call(),
  "DataViewPrototypeGetInt8": Function bound call(),
  "DataViewPrototypeGetUint16": Function bound call(),
  "DataViewPrototypeGetUint32": Function bound call(),
  "DataViewPrototypeGetUint8": Function bound call(),
  "DataViewPrototypeSetBigInt64": Function bound call(),
  "DataViewPrototypeSetBigUint64": Function bound call(),
  "DataViewPrototypeSetFloat32": Function bound call(),
  "DataViewPrototypeSetFloat64": Function bound call(),
  "DataViewPrototypeSetInt16": Function bound call(),
  "DataViewPrototypeSetInt32": Function bound call(),
  "DataViewPrototypeSetInt8": Function bound call(),
  "DataViewPrototypeSetUint16": Function bound call(),
  "DataViewPrototypeSetUint32": Function bound call(),
  "DataViewPrototypeSetUint8": Function bound call(),
  "DataViewPrototypeSymbolToStringTag": "DataView",
  "Date": Function Date(),
  "DateLength": 7,
  "DateName": "Date",
  "DateNow": Function (...args),
  "DateParse": Function (...args),
  "DatePrototype": Object {},
  "DatePrototypeGetDate": Function bound call(),
  "DatePrototypeGetDay": Function bound call(),
  "DatePrototypeGetFullYear": Function bound call(),
  "DatePrototypeGetHours": Function bound call(),
  "DatePrototypeGetMilliseconds": Function bound call(),
  "DatePrototypeGetMinutes": Function bound call(),
  "DatePrototypeGetMonth": Function bound call(),
  "DatePrototypeGetSeconds": Function bound call(),
  "DatePrototypeGetTime": Function bound call(),
  "DatePrototypeGetTimezoneOffset": Function bound call(),
  "DatePrototypeGetUTCDate": Function bound call(),
  "DatePrototypeGetUTCDay": Function bound call(),
  "DatePrototypeGetUTCFullYear": Function bound call(),
  "DatePrototypeGetUTCHours": Function bound call(),
  "DatePrototypeGetUTCMilliseconds": Function bound call(),
  "DatePrototypeGetUTCMinutes": Function bound call(),
  "DatePrototypeGetUTCMonth": Function bound call(),
  "DatePrototypeGetUTCSeconds": Function bound call(),
  "DatePrototypeGetYear": Function bound call(),
  "DatePrototypeSetDate": Function bound call(),
  "DatePrototypeSetFullYear": Function bound call(),
  "DatePrototypeSetHours": Function bound call(),
  "DatePrototypeSetMilliseconds": Function bound call(),
  "DatePrototypeSetMinutes": Function bound call(),
  "DatePrototypeSetMonth": Function bound call(),
  "DatePrototypeSetSeconds": Function bound call(),
  "DatePrototypeSetTime": Function bound call(),
  "DatePrototypeSetUTCDate": Function bound call(),
  "DatePrototypeSetUTCFullYear": Function bound call(),
  "DatePrototypeSetUTCHours": Function bound call(),
  "DatePrototypeSetUTCMilliseconds": Function bound call(),
  "DatePrototypeSetUTCMinutes": Function bound call(),
  "DatePrototypeSetUTCMonth": Function bound call(),
  "DatePrototypeSetUTCSeconds": Function bound call(),
  "DatePrototypeSetYear": Function bound call(),
  "DatePrototypeSymbolToPrimitive": Function bound call(),
  "DatePrototypeToDateString": Function bound call(),
  "DatePrototypeToGMTString": Function bound call(),
  "DatePrototypeToISOString": Function bound call(),
  "DatePrototypeToJSON": Function bound call(),
  "DatePrototypeToLocaleDateString": Function bound call(),
  "DatePrototypeToLocaleString": Function bound call(),
  "DatePrototypeToLocaleTimeString": Function bound call(),
  "DatePrototypeToString": Function bound call(),
  "DatePrototypeToTimeString": Function bound call(),
  "DatePrototypeToUTCString": Function bound call(),
  "DatePrototypeValueOf": Function bound call(),
  "DateUTC": Function (...args),
  "decodeURI": Function decodeURI(),
  "decodeURIComponent": Function decodeURIComponent(),
  "encodeURI": Function encodeURI(),
  "encodeURIComponent": Function encodeURIComponent(),
  "Error": Function Error(),
  "ErrorCaptureStackTrace": Function (...args),
  "ErrorLength": 1,
  "ErrorName": "Error",
  "ErrorPrototype": Object {},
  "ErrorPrototypeMessage": "",
  "ErrorPrototypeName": "Error",
  "ErrorPrototypeToString": Function bound call(),
  "ErrorStackTraceLimit": 10,
  "escape": Function escape(),
  "eval": Function eval(),
  "EvalError": Function EvalError(),
  "EvalErrorLength": 1,
  "EvalErrorName": "EvalError",
  "EvalErrorPrototype": Object {},
  "EvalErrorPrototypeMessage": "",
  "EvalErrorPrototypeName": "EvalError",
  "FinalizationRegistry": Function FinalizationRegistry(),
  "FinalizationRegistryLength": 1,
  "FinalizationRegistryName": "FinalizationRegistry",
  "FinalizationRegistryPrototype": Object {},
  "FinalizationRegistryPrototypeRegister": Function bound call(),
  "FinalizationRegistryPrototypeSymbolToStringTag": "FinalizationRegistry",
  "FinalizationRegistryPrototypeUnregister": Function bound call(),
  "Float32Array": Function Float32Array(),
  "Float32ArrayBYTES_PER_ELEMENT": 4,
  "Float32ArrayLength": 3,
  "Float32ArrayName": "Float32Array",
  "Float32ArrayPrototype": Object {},
  "Float32ArrayPrototypeBYTES_PER_ELEMENT": 4,
  "Float64Array": Function Float64Array(),
  "Float64ArrayBYTES_PER_ELEMENT": 8,
  "Float64ArrayLength": 3,
  "Float64ArrayName": "Float64Array",
  "Float64ArrayPrototype": Object {},
  "Float64ArrayPrototypeBYTES_PER_ELEMENT": 8,
  "Function": Function Function(),
  "FunctionLength": 1,
  "FunctionName": "Function",
  "FunctionPrototype": Object {},
  "FunctionPrototypeApply": Function bound call(),
  "FunctionPrototypeBind": Function bound call(),
  "FunctionPrototypeCall": Function bound call(),
  "FunctionPrototypeGetArguments": Function bound call(),
  "FunctionPrototypeGetCaller": Function bound call(),
  "FunctionPrototypeLength": 0,
  "FunctionPrototypeName": "",
  "FunctionPrototypeSetArguments": Function bound call(),
  "FunctionPrototypeSetCaller": Function bound call(),
  "FunctionPrototypeSymbolHasInstance": Function bound call(),
  "FunctionPrototypeToString": Function bound call(),
  "globalThis": "<<globalThis>>",
  "hardenRegExp": Function hardenRegExp(re),
  "Int16Array": Function Int16Array(),
  "Int16ArrayBYTES_PER_ELEMENT": 2,
  "Int16ArrayLength": 3,
  "Int16ArrayName": "Int16Array",
  "Int16ArrayPrototype": Object {},
  "Int16ArrayPrototypeBYTES_PER_ELEMENT": 2,
  "Int32Array": Function Int32Array(),
  "Int32ArrayBYTES_PER_ELEMENT": 4,
  "Int32ArrayLength": 3,
  "Int32ArrayName": "Int32Array",
  "Int32ArrayPrototype": Object {},
  "Int32ArrayPrototypeBYTES_PER_ELEMENT": 4,
  "Int8Array": Function Int8Array(),
  "Int8ArrayBYTES_PER_ELEMENT": 1,
  "Int8ArrayLength": 3,
  "Int8ArrayName": "Int8Array",
  "Int8ArrayPrototype": Object {},
  "Int8ArrayPrototypeBYTES_PER_ELEMENT": 1,
  "JSON": Object {},
  "JSONParse": Function (...args),
  "JSONStringify": Function (...args),
  "JSONSymbolToStringTag": "JSON",
  "makeSafe": Function makeSafe(unsafe, safe),
  "Map": Function Map(),
  "MapGetSymbolSpecies": Function bound call(),
  "MapLength": 0,
  "MapName": "Map",
  "MapPrototype": Object {},
  "MapPrototypeClear": Function bound call(),
  "MapPrototypeDelete": Function bound call(),
  "MapPrototypeEntries": Function bound call(),
  "MapPrototypeForEach": Function bound call(),
  "MapPrototypeGet": Function bound call(),
  "MapPrototypeGetSize": Function bound call(),
  "MapPrototypeHas": Function bound call(),
  "MapPrototypeKeys": Function bound call(),
  "MapPrototypeSet": Function bound call(),
  "MapPrototypeSymbolIterator": Function bound call(),
  "MapPrototypeSymbolToStringTag": "Map",
  "MapPrototypeValues": Function bound call(),
  "Math": Object {},
  "MathAbs": Function abs(),
  "MathAcos": Function acos(),
  "MathAcosh": Function acosh(),
  "MathAsin": Function asin(),
  "MathAsinh": Function asinh(),
  "MathAtan": Function atan(),
  "MathAtan2": Function atan2(),
  "MathAtanh": Function atanh(),
  "MathCbrt": Function cbrt(),
  "MathCeil": Function ceil(),
  "MathClz32": Function clz32(),
  "MathCos": Function cos(),
  "MathCosh": Function cosh(),
  "MathE": 2.718281828459045,
  "MathExp": Function exp(),
  "MathExpm1": Function expm1(),
  "MathFloor": Function floor(),
  "MathFround": Function fround(),
  "MathHypot": Function hypot(),
  "MathHypotApply": Function bound apply(),
  "MathImul": Function imul(),
  "MathLN10": 2.302585092994046,
  "MathLN2": 0.6931471805599453,
  "MathLog": Function log(),
  "MathLog10": Function log10(),
  "MathLOG10E": 0.4342944819032518,
  "MathLog1p": Function log1p(),
  "MathLog2": Function log2(),
  "MathLOG2E": 1.4426950408889634,
  "MathMax": Function max(),
  "MathMaxApply": Function bound apply(),
  "MathMin": Function min(),
  "MathMinApply": Function bound apply(),
  "MathPI": 3.141592653589793,
  "MathPow": Function pow(),
  "MathRandom": Function random(),
  "MathRound": Function round(),
  "MathSign": Function sign(),
  "MathSin": Function sin(),
  "MathSinh": Function sinh(),
  "MathSqrt": Function sqrt(),
  "MathSQRT1_2": 0.7071067811865476,
  "MathSQRT2": 1.4142135623730951,
  "MathSymbolToStringTag": "Math",
  "MathTan": Function tan(),
  "MathTanh": Function tanh(),
  "MathTrunc": Function trunc(),
  "maybeStaticCall": Function maybeStaticCall(fn),
  "Number": Function Number(),
  "NumberEPSILON": 2.220446049250313e-16,
  "NumberIsFinite": Function (...args),
  "NumberIsInteger": Function (...args),
  "NumberIsNaN": Function (...args),
  "NumberIsSafeInteger": Function (...args),
  "NumberLength": 1,
  "NumberMAX_SAFE_INTEGER": 9007199254740991,
  "NumberMAX_VALUE": 1.7976931348623157e+308,
  "NumberMIN_SAFE_INTEGER": -9007199254740991,
  "NumberMIN_VALUE": 5e-324,
  "NumberName": "Number",
  "NumberNaN": null,
  "NumberNEGATIVE_INFINITY": null,
  "NumberParseFloat": Function (...args),
  "NumberParseInt": Function (...args),
  "NumberPOSITIVE_INFINITY": null,
  "NumberPrototype": Object {},
  "NumberPrototypeToExponential": Function bound call(),
  "NumberPrototypeToFixed": Function bound call(),
  "NumberPrototypeToLocaleString": Function bound call(),
  "NumberPrototypeToPrecision": Function bound call(),
  "NumberPrototypeToString": Function bound call(),
  "NumberPrototypeValueOf": Function bound call(),
  "Object": Function Object(),
  "ObjectAssign": Function (...args),
  "ObjectCreate": Function (...args),
  "ObjectDefineProperties": Function (...args),
  "ObjectDefineProperty": Function (...args),
  "ObjectEntries": Function (...args),
  "ObjectFreeze": Function (...args),
  "ObjectFromEntries": Function (...args),
  "ObjectGetOwnPropertyDescriptor": Function (...args),
  "ObjectGetOwnPropertyDescriptors": Function (...args),
  "ObjectGetOwnPropertyNames": Function (...args),
  "ObjectGetOwnPropertySymbols": Function (...args),
  "ObjectGetPrototypeOf": Function (...args),
  "ObjectIs": Function (...args),
  "ObjectIsExtensible": Function (...args),
  "ObjectIsFrozen": Function (...args),
  "ObjectIsSealed": Function (...args),
  "ObjectKeys": Function (...args),
  "ObjectLength": 1,
  "ObjectName": "Object",
  "ObjectPreventExtensions": Function (...args),
  "ObjectPrototype": Object {},
  "ObjectPrototype__defineGetter__": Function bound call(),
  "ObjectPrototype__defineSetter__": Function bound call(),
  "ObjectPrototype__lookupGetter__": Function bound call(),
  "ObjectPrototype__lookupSetter__": Function bound call(),
  "ObjectPrototypeGet__proto__": Function bound call(),
  "ObjectPrototypeHasOwnProperty": Function bound call(),
  "ObjectPrototypeIsPrototypeOf": Function bound call(),
  "ObjectPrototypePropertyIsEnumerable": Function bound call(),
  "ObjectPrototypeSet__proto__": Function bound call(),
  "ObjectPrototypeToLocaleString": Function bound call(),
  "ObjectPrototypeToString": Function bound call(),
  "ObjectPrototypeValueOf": Function bound call(),
  "ObjectSeal": Function (...args),
  "ObjectSetPrototypeOf": Function (...args),
  "ObjectValues": Function (...args),
  "process": "object",
  "processAbort": "function",
  "processAllowedNodeEnvironmentFlags": "object",
  "processArch": "string",
  "processArgv": "object",
  "processArgv0": "string",
  "processCwd": "function",
  "processDebugPort": "number",
  "processEmitWarning": "function",
  "processEnv": "object",
  "processExecArgv": "object",
  "processExecPath": "string",
  "processExitCode": "undefined",
  "processFeatures": "object",
  "processHasUncaughtExceptionCaptureCallback": "function",
  "processModuleLoadList": "object",
  "processNextTick": "function",
  "processPid": "number",
  "processPlatform": "string",
  "processPpid": "number",
  "processRelease": "object",
  "processReport": "object",
  "processSetegid": "<<undefined on windows>>",
  "processSeteuid": "<<undefined on windows>>",
  "processSetgid": "<<undefined on windows>>",
  "processSetgroups": "<<undefined on windows>>",
  "processSetSourceMapsEnabled": "function",
  "processSetuid": "<<undefined on windows>>",
  "processSetUncaughtExceptionCaptureCallback": "function",
  "processsInitgroups": "<<undefined on windows>>",
  "processStderr": "object",
  "processStdin": "object",
  "processStdout": "object",
  "processTitle": "string",
  "processUmask": "function",
  "processVersion": "string",
  "processVersions": "object",
  "Promise": Function Promise(),
  "PromiseAll": Function all(),
  "PromiseAllSettled": Function allSettled(),
  "PromiseAny": "<<undefined in node 14>>",
  "PromiseGetSymbolSpecies": Function bound call(),
  "PromiseLength": 1,
  "PromiseName": "Promise",
  "PromisePrototype": Object {},
  "PromisePrototypeCatch": Function bound call(),
  "PromisePrototypeFinally": Function bound call(),
  "PromisePrototypeSymbolToStringTag": "Promise",
  "PromisePrototypeThen": Function bound call(),
  "PromiseRace": Function race(),
  "PromiseReject": Function reject(),
  "PromiseResolve": Function resolve(),
  "Proxy": Function Proxy(),
  "ProxyLength": 2,
  "ProxyName": "Proxy",
  "ProxyRevocable": Function (...args),
  "RangeError": Function RangeError(),
  "RangeErrorLength": 1,
  "RangeErrorName": "RangeError",
  "RangeErrorPrototype": Object {},
  "RangeErrorPrototypeMessage": "",
  "RangeErrorPrototypeName": "RangeError",
  "ReferenceError": Function ReferenceError(),
  "ReferenceErrorLength": 1,
  "ReferenceErrorName": "ReferenceError",
  "ReferenceErrorPrototype": Object {},
  "ReferenceErrorPrototypeMessage": "",
  "ReferenceErrorPrototypeName": "ReferenceError",
  "Reflect": Object {},
  "ReflectApply": Function apply(),
  "ReflectConstruct": Function construct(),
  "ReflectDefineProperty": Function defineProperty(),
  "ReflectDeleteProperty": Function deleteProperty(),
  "ReflectGet": Function get(),
  "ReflectGetOwnPropertyDescriptor": Function getOwnPropertyDescriptor(),
  "ReflectGetPrototypeOf": Function getPrototypeOf(),
  "ReflectHas": Function has(),
  "ReflectIsExtensible": Function isExtensible(),
  "ReflectOwnKeys": Function ownKeys(),
  "ReflectPreventExtensions": Function preventExtensions(),
  "ReflectSet": Function set(),
  "ReflectSetPrototypeOf": Function setPrototypeOf(),
  "ReflectSymbolToStringTag": "Reflect",
  "RegExp": Function RegExp(),
  "RegExpGet$_": Function bound call(),
  "RegExpGet$'": Function bound call(),
  "RegExpGet$&": Function bound call(),
  "RegExpGet$\`": Function bound call(),
  "RegExpGet$+": Function bound call(),
  "RegExpGet$1": Function bound call(),
  "RegExpGet$2": Function bound call(),
  "RegExpGet$3": Function bound call(),
  "RegExpGet$4": Function bound call(),
  "RegExpGet$5": Function bound call(),
  "RegExpGet$6": Function bound call(),
  "RegExpGet$7": Function bound call(),
  "RegExpGet$8": Function bound call(),
  "RegExpGet$9": Function bound call(),
  "RegExpGetDollarAmp": Function bound call(),
  "RegExpGetDollarPlus": Function bound call(),
  "RegExpGetDollarSquo": Function bound call(),
  "RegExpGetDollarTick": Function bound call(),
  "RegExpGetInput": Function bound call(),
  "RegExpGetLastMatch": Function bound call(),
  "RegExpGetLastParen": Function bound call(),
  "RegExpGetLeftContext": Function bound call(),
  "RegExpGetRightContext": Function bound call(),
  "RegExpGetSymbolSpecies": Function bound call(),
  "RegExpLength": 2,
  "RegExpName": "RegExp",
  "RegExpPrototype": Object {},
  "RegExpPrototypeCompile": Function bound call(),
  "RegExpPrototypeExec": Function bound call(),
  "RegExpPrototypeGetDotAll": Function bound call(),
  "RegExpPrototypeGetFlags": Function bound call(),
  "RegExpPrototypeGetGlobal": Function bound call(),
  "RegExpPrototypeGetHasIndices": Function bound call(),
  "RegExpPrototypeGetIgnoreCase": Function bound call(),
  "RegExpPrototypeGetMultiline": Function bound call(),
  "RegExpPrototypeGetSource": Function bound call(),
  "RegExpPrototypeGetSticky": Function bound call(),
  "RegExpPrototypeGetUnicode": Function bound call(),
  "RegExpPrototypeSymbolMatch": Function bound call(),
  "RegExpPrototypeSymbolMatchAll": Function bound call(),
  "RegExpPrototypeSymbolReplace": Function bound call(),
  "RegExpPrototypeSymbolSearch": Function bound call(),
  "RegExpPrototypeSymbolSplit": Function bound call(),
  "RegExpPrototypeTest": Function bound call(),
  "RegExpPrototypeToString": Function bound call(),
  "RegExpSet$_": Function bound call(),
  "RegExpSet$'": Function bound call(),
  "RegExpSet$&": Function bound call(),
  "RegExpSet$\`": Function bound call(),
  "RegExpSet$+": Function bound call(),
  "RegExpSet$1": Function bound call(),
  "RegExpSet$2": Function bound call(),
  "RegExpSet$3": Function bound call(),
  "RegExpSet$4": Function bound call(),
  "RegExpSet$5": Function bound call(),
  "RegExpSet$6": Function bound call(),
  "RegExpSet$7": Function bound call(),
  "RegExpSet$8": Function bound call(),
  "RegExpSet$9": Function bound call(),
  "RegExpSetDollarAmp": Function bound call(),
  "RegExpSetDollarPlus": Function bound call(),
  "RegExpSetDollarSquo": Function bound call(),
  "RegExpSetDollarTick": Function bound call(),
  "RegExpSetInput": Function bound call(),
  "RegExpSetLastMatch": Function bound call(),
  "RegExpSetLastParen": Function bound call(),
  "RegExpSetLeftContext": Function bound call(),
  "RegExpSetRightContext": Function bound call(),
  "SafeFinalizationRegistry": Function SafeFinalizationRegistry(classSafeFinalizationRegistryextendsFinalizationRegistry),
  "SafeMap": Function SafeMap(classSafeMapextendsMap),
  "SafePromise": Function SafePromise(classSafePromiseextendsPromise),
  "SafeSet": Function SafeSet(classSafeSetextendsSet),
  "SafeWeakMap": Function SafeWeakMap(classSafeWeakMapextendsWeakMap),
  "SafeWeakRef": Function SafeWeakRef(classSafeWeakRefextendsWeakRef),
  "SafeWeakSet": Function SafeWeakSet(classSafeWeakSetextendsWeakSet),
  "Set": Function Set(),
  "SetGetSymbolSpecies": Function bound call(),
  "setImmediate": Function (...args),
  "setInterval": Function (...args),
  "SetLength": 0,
  "SetName": "Set",
  "SetPrototype": Object {},
  "SetPrototypeAdd": Function bound call(),
  "SetPrototypeClear": Function bound call(),
  "SetPrototypeDelete": Function bound call(),
  "SetPrototypeEntries": Function bound call(),
  "SetPrototypeForEach": Function bound call(),
  "SetPrototypeGetSize": Function bound call(),
  "SetPrototypeHas": Function bound call(),
  "SetPrototypeKeys": Function bound call(),
  "SetPrototypeSymbolIterator": Function bound call(),
  "SetPrototypeSymbolToStringTag": "Set",
  "SetPrototypeValues": Function bound call(),
  "setTimeout": Function (...args),
  "staticApply": Function staticApply(fn),
  "staticCall": Function staticCall(fn),
  "String": Function String(),
  "StringFromCharCode": Function fromCharCode(),
  "StringFromCharCodeApply": Function bound apply(),
  "StringFromCodePoint": Function fromCodePoint(),
  "StringFromCodePointApply": Function bound apply(),
  "StringIterator": Object {
    "prototype": Object {},
  },
  "StringIteratorPrototype": "<<seen>>",
  "StringIteratorPrototypeNext": Function bound call(),
  "StringIteratorPrototypeSymbolToStringTag": "String Iterator",
  "StringLength": 1,
  "StringName": "String",
  "StringPrototype": Object {},
  "StringPrototypeAnchor": Function bound call(),
  "StringPrototypeBig": Function bound call(),
  "StringPrototypeBlink": Function bound call(),
  "StringPrototypeBold": Function bound call(),
  "StringPrototypeCharAt": Function bound call(),
  "StringPrototypeCharCodeAt": Function bound call(),
  "StringPrototypeCodePointAt": Function bound call(),
  "StringPrototypeConcat": Function bound call(),
  "StringPrototypeConcatApply": Function bound apply(),
  "StringPrototypeEndsWith": Function bound call(),
  "StringPrototypeFixed": Function bound call(),
  "StringPrototypeFontcolor": Function bound call(),
  "StringPrototypeFontsize": Function bound call(),
  "StringPrototypeIncludes": Function bound call(),
  "StringPrototypeIndexOf": Function bound call(),
  "StringPrototypeItalics": Function bound call(),
  "StringPrototypeLastIndexOf": Function bound call(),
  "StringPrototypeLength": 0,
  "StringPrototypeLink": Function bound call(),
  "StringPrototypeLocaleCompare": Function bound call(),
  "StringPrototypeMatch": Function bound call(),
  "StringPrototypeMatchAll": Function bound call(),
  "StringPrototypeNormalize": Function bound call(),
  "StringPrototypePadEnd": Function bound call(),
  "StringPrototypePadStart": Function bound call(),
  "StringPrototypeRepeat": Function bound call(),
  "StringPrototypeReplace": Function bound call(),
  "StringPrototypeReplaceAll": Function bound call(),
  "StringPrototypeSearch": Function bound call(),
  "StringPrototypeSlice": Function bound call(),
  "StringPrototypeSmall": Function bound call(),
  "StringPrototypeSplit": Function bound call(),
  "StringPrototypeStartsWith": Function bound call(),
  "StringPrototypeStrike": Function bound call(),
  "StringPrototypeSub": Function bound call(),
  "StringPrototypeSubstr": Function bound call(),
  "StringPrototypeSubstring": Function bound call(),
  "StringPrototypeSup": Function bound call(),
  "StringPrototypeSymbolIterator": Function bound call(),
  "StringPrototypeToLocaleLowerCase": Function bound call(),
  "StringPrototypeToLocaleUpperCase": Function bound call(),
  "StringPrototypeToLowerCase": Function bound call(),
  "StringPrototypeToString": Function bound call(),
  "StringPrototypeToUpperCase": Function bound call(),
  "StringPrototypeTrim": Function bound call(),
  "StringPrototypeTrimEnd": Function bound call(),
  "StringPrototypeTrimLeft": Function bound call(),
  "StringPrototypeTrimRight": Function bound call(),
  "StringPrototypeTrimStart": Function bound call(),
  "StringPrototypeValueOf": Function bound call(),
  "StringRaw": Function raw(),
  "Symbol": Function Symbol(),
  "SymbolAsyncIterator": Symbol(Symbol.asyncIterator),
  "SymbolFor": Function for(),
  "SymbolHasInstance": Symbol(Symbol.hasInstance),
  "SymbolIsConcatSpreadable": Symbol(Symbol.isConcatSpreadable),
  "SymbolIterator": Symbol(Symbol.iterator),
  "SymbolKeyFor": Function keyFor(),
  "SymbolLength": 0,
  "SymbolMatch": Symbol(Symbol.match),
  "SymbolMatchAll": Symbol(Symbol.matchAll),
  "SymbolName": "Symbol",
  "SymbolPrototype": Object {},
  "SymbolPrototypeGetDescription": Function bound call(),
  "SymbolPrototypeSymbolToPrimitive": Function bound call(),
  "SymbolPrototypeSymbolToStringTag": "Symbol",
  "SymbolPrototypeToString": Function bound call(),
  "SymbolPrototypeValueOf": Function bound call(),
  "SymbolReplace": Symbol(Symbol.replace),
  "SymbolSearch": Symbol(Symbol.search),
  "SymbolSpecies": Symbol(Symbol.species),
  "SymbolSplit": Symbol(Symbol.split),
  "SymbolToPrimitive": Symbol(Symbol.toPrimitive),
  "SymbolToStringTag": Symbol(Symbol.toStringTag),
  "SymbolUnscopables": Symbol(Symbol.unscopables),
  "SyntaxError": Function SyntaxError(),
  "SyntaxErrorLength": 1,
  "SyntaxErrorName": "SyntaxError",
  "SyntaxErrorPrototype": Object {},
  "SyntaxErrorPrototypeMessage": "",
  "SyntaxErrorPrototypeName": "SyntaxError",
  "TypedArray": Function TypedArray(),
  "TypedArrayFrom": Function TypedArrayFrom(ctor, ...args),
  "TypedArrayGetSymbolSpecies": Function bound call(),
  "TypedArrayLength": 0,
  "TypedArrayName": "TypedArray",
  "TypedArrayOf": Function TypedArrayOf(ctor, ...args),
  "TypedArrayOfApply": Function TypedArrayOfApply(ctor, args),
  "TypedArrayPrototype": Object {},
  "TypedArrayPrototypeCopyWithin": Function bound call(),
  "TypedArrayPrototypeEntries": Function bound call(),
  "TypedArrayPrototypeEvery": Function bound call(),
  "TypedArrayPrototypeFill": Function bound call(),
  "TypedArrayPrototypeFilter": Function bound call(),
  "TypedArrayPrototypeFind": Function bound call(),
  "TypedArrayPrototypeFindIndex": Function bound call(),
  "TypedArrayPrototypeForEach": Function bound call(),
  "TypedArrayPrototypeGetBuffer": Function bound call(),
  "TypedArrayPrototypeGetByteLength": Function bound call(),
  "TypedArrayPrototypeGetByteOffset": Function bound call(),
  "TypedArrayPrototypeGetLength": Function bound call(),
  "TypedArrayPrototypeGetSymbolToStringTag": Function TypedArrayPrototypeGetSymbolToStringTag(self),
  "TypedArrayPrototypeIncludes": Function bound call(),
  "TypedArrayPrototypeIndexOf": Function bound call(),
  "TypedArrayPrototypeJoin": Function bound call(),
  "TypedArrayPrototypeKeys": Function bound call(),
  "TypedArrayPrototypeLastIndexOf": Function bound call(),
  "TypedArrayPrototypeMap": Function bound call(),
  "TypedArrayPrototypeReduce": Function bound call(),
  "TypedArrayPrototypeReduceRight": Function bound call(),
  "TypedArrayPrototypeReverse": Function bound call(),
  "TypedArrayPrototypeSet": Function bound call(),
  "TypedArrayPrototypeSlice": Function bound call(),
  "TypedArrayPrototypeSome": Function bound call(),
  "TypedArrayPrototypeSort": Function bound call(),
  "TypedArrayPrototypeSubarray": Function bound call(),
  "TypedArrayPrototypeSymbolIterator": Function bound call(),
  "TypedArrayPrototypeToLocaleString": Function bound call(),
  "TypedArrayPrototypeToString": Function bound call(),
  "TypedArrayPrototypeValues": Function bound call(),
  "TypeError": Function TypeError(),
  "TypeErrorLength": 1,
  "TypeErrorName": "TypeError",
  "TypeErrorPrototype": Object {},
  "TypeErrorPrototypeMessage": "",
  "TypeErrorPrototypeName": "TypeError",
  "Uint16Array": Function Uint16Array(),
  "Uint16ArrayBYTES_PER_ELEMENT": 2,
  "Uint16ArrayLength": 3,
  "Uint16ArrayName": "Uint16Array",
  "Uint16ArrayPrototype": Object {},
  "Uint16ArrayPrototypeBYTES_PER_ELEMENT": 2,
  "Uint32Array": Function Uint32Array(),
  "Uint32ArrayBYTES_PER_ELEMENT": 4,
  "Uint32ArrayLength": 3,
  "Uint32ArrayName": "Uint32Array",
  "Uint32ArrayPrototype": Object {},
  "Uint32ArrayPrototypeBYTES_PER_ELEMENT": 4,
  "Uint8Array": Function Uint8Array(),
  "Uint8ArrayBYTES_PER_ELEMENT": 1,
  "Uint8ArrayLength": 3,
  "Uint8ArrayName": "Uint8Array",
  "Uint8ArrayPrototype": Object {},
  "Uint8ArrayPrototypeBYTES_PER_ELEMENT": 1,
  "Uint8ClampedArray": Function Uint8ClampedArray(),
  "Uint8ClampedArrayBYTES_PER_ELEMENT": 1,
  "Uint8ClampedArrayLength": 3,
  "Uint8ClampedArrayName": "Uint8ClampedArray",
  "Uint8ClampedArrayPrototype": Object {},
  "Uint8ClampedArrayPrototypeBYTES_PER_ELEMENT": 1,
  "uncurryGetter": Function uncurryGetter(obj, k),
  "uncurryMethod": Function uncurryMethod(obj, k),
  "uncurrySetter": Function uncurrySetter(obj, k),
  "uncurryThis": Function bound bind(),
  "unescape": Function unescape(),
  "URIError": Function URIError(),
  "URIErrorLength": 1,
  "URIErrorName": "URIError",
  "URIErrorPrototype": Object {},
  "URIErrorPrototypeMessage": "",
  "URIErrorPrototypeName": "URIError",
  "URL": Function URL(classURL),
  "URLCreateObjectURL": Function (...args),
  "URLRevokeObjectURL": Function (...args),
  "WeakMap": Function WeakMap(),
  "WeakMapLength": 0,
  "WeakMapName": "WeakMap",
  "WeakMapPrototype": Object {},
  "WeakMapPrototypeDelete": Function bound call(),
  "WeakMapPrototypeGet": Function bound call(),
  "WeakMapPrototypeHas": Function bound call(),
  "WeakMapPrototypeSet": Function bound call(),
  "WeakMapPrototypeSymbolToStringTag": "WeakMap",
  "WeakRef": Function WeakRef(),
  "WeakRefLength": 1,
  "WeakRefName": 1,
  "WeakRefPrototype": Object {},
  "WeakRefPrototypeDeref": Function bound call(),
  "WeakRefPrototypeSymbolToStringTag": "WeakRef",
  "WeakSet": Function WeakSet(),
  "WeakSetLength": 0,
  "WeakSetName": "WeakSet",
  "WeakSetPrototype": Object {},
  "WeakSetPrototypeAdd": Function bound call(),
  "WeakSetPrototypeDelete": Function bound call(),
  "WeakSetPrototypeHas": Function bound call(),
  "WeakSetPrototypeSymbolToStringTag": "WeakSet",
}
`
